apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-app
spec:
  environments:
    - name: dev
      build:
        from: main
    - name: prod
      build:
        from: release
    - name: demo
  components:
    - name: server
      src: ./backend
      ports:
        - name: http
          port: 3000
      variables:
        PORT: 3000
        APP_VARIABLE: "common"
      environmentConfig:
        - environment: demo
          variables:
            APP_VARIABLE: "Demo app variable"
    - name: www
      src: ./frontend
      ports:
        - name: http
          port: 3001
      publicPort: http
      resources:
        requests:
          memory: "100Mi"
          cpu: "50m"
        limits:
          memory: "100Mi"
          cpu: "50m"
      variables:
        PORT: 3001
        ECHO_URL: "http://server:3000"
      environmentConfig:
        - environment: dev
          replicas: 2
          horizontalScaling:
            minReplicas: 2
            maxReplicas: 5
        - environment: prod
          horizontalScaling:
            minReplicas: 2
            maxReplicas: 5
  dnsAppAlias:
    environment: dev
    component: www