apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-app
spec:
  environments:
    - name: dev
      build:
        from: main
  components:
    - name: server
      src: ./backend
      ports:
        - name: http
          port: 3000
      variables:
        PORT: 3000
    - name: www
      src: ./frontend
      ports:
        - name: http
          port: 3001
      publicPort: http
      variables:
        PORT: 3001
        ECHO_URL: "http://server:3000"
