apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-app
spec:
  environments:
    - name: development
      build:
        from: main
    - name: prod
      build:
        from: release
  components:
    - name: server
      src: ./backend
      ports:
        - name: http
          port: 3000
      variables:
        PORT: 3000
      environmentConfig:
        - environment: prod
          variables:
            NODE_ENV: production
    - name: www
      src: ./frontend
      ports:
        - name: http
          port: 3001
      publicPort: http
      variables:
        PORT: 3001
        ECHO_URL: "http://server:3000"
      environmentConfig:
        - environment: development
          replicas: 2
        - environment: prod
          horizontalScaling:
            minReplicas: 2
            maxReplicas: 5
          variables:
            NODE_ENV: production
  dnsAppAlias:
    environment: prod
    component: www